[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
board_build.f_cpu = 260000000L
monitor_speed = 115200
board_build.filesystem_size = 1m

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.0
    lvgl/lvgl @ ^8.3.11

build_flags =
    -O3
    -funroll-loops
    -ffast-math
    -Wno-deprecated-declarations
    -Iinclude
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_18=1
    -D LV_FONT_MONTSERRAT_48=1
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_INVERSION_ON
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_MISO=12
    -D TFT_MOSI=11
    -D TFT_SCLK=10
    -D TFT_CS=9
    -D TFT_DC=8
    -D TFT_RST=15
    -D TFT_BL=13
    -D TFT_BACKLIGHT_ON=HIGH
    -D RP2040_PIO_SPI=1
    -D SPI_FREQUENCY=50000000
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1